name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/godot-ci.yml
    with:
      project_path: tests/godot-ci-test
    
  tests:
    uses: ./.github/workflows/godot-tests.yml
    with:
      project_path: tests/godot-tests-test